[project]
name = "poc-llm-query-to-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.49.1",
    "openai>=2.0.1",
    "pandas>=2.3.3",
    "pytest>=8.4.2",
    "ruff>=0.14.0",
    "typer[all]>=0.19.2",
]
